name: lint and format

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8
    - name: check formatting with black
      run: |
        python -m black --diff src scripts
    - name: lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        python -m flake8 . --count --exit-zero --statistics
